### ISSUE TITLE
Marvel & DC bootanimation

### ISSUE THREAD

**Issue by jplwolters** [topjohnwu/Magisk_Repo_Submissions#149]
https://github.com/jplwolters/Marvel-and-DC-bootanimation
Changes stock bootanimation to an incredibly new one.

**Comment by topjohnwu** [comment]
Does this work properly? Boot animations most likely requires `post-fs` mode, which does not have modules support.

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/jplwolters/Marvel-and-DC-bootanimation) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
