### ISSUE TITLE
Sudo4Droid Module Submission

### ISSUE THREAD

**Issue by PorygonZRocks** [topjohnwu/Magisk_Repo_Submissions#162]
This module adds a sudo command (actually a script calling su -c). The repo is at https://gitlab.com/PorygonZRocks/sudo4droid-magisk. I've checked the permissions, and it is public this time.

**Comment by topjohnwu** [comment]
Bad Request: No GitHub link found!

**Comment by PorygonZRocks** [comment]
It has to be GitHub? You can mirror from GitLab.
