### ISSUE TITLE
[UPDATE] ExSDCard Write Access Enabler v2.1

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk_Repo_Submissions#164]
https://github.com/xerta555/ExSDCard-Write-Access-Enabler-Nougat-v2.1

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/xerta555/ExSDCard-Write-Access-Enabler-Nougat-v2.1) is not a valid Magisk Module!
Reason: Invalid prop `versionCode`: 2.1
