### ISSUE TITLE
[UPDATE TO 1400] Systemlessly Font with Tsukushimarugo-A(CJK) & sleek

### ISSUE THREAD

**Issue by HUMORCE** [topjohnwu/Magisk_Repo_Submissions#165]
https://github.com/HUMORCE/Systemlessly-Font-with-Tsukushimarugo-A-CJK-Sleek

update to 1400 .
the module has been removed , please add it back to central .

**Comment by topjohnwu** [comment]
New repo added: [Systemlessly-Font-with-Tsukushimarugo-A-CJK-Sleek](https://github.com/Magisk-Modules-Repo/Systemlessly-Font-with-Tsukushimarugo-A-CJK-Sleek), please accept the collaboration invitation in your email
