### ISSUE TITLE
Pixel Wifi mod

### ISSUE THREAD

**Issue by RogerF81** [topjohnwu/Magisk_Repo_Submissions#167]
[Link to repo](https://github.com/RogerF81/pennygetyourownwifi)

This module replaces the /system/etc/wifi/WCNSS_qcom_cfg.ini file with the stock Pixel file. Wifi is supposed to be more stable thanks to that. Confirmed fully working on HTC 10 and the OnePlus 5 without any issues.

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/RogerF81/pennygetyourownwifi)) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
