### ISSUE TITLE
[Module Submission] Magisk Google DNS

### ISSUE THREAD

**Issue by tfae** [topjohnwu/Magisk_Repo_Submissions#168]
https://github.com/tfae/magisk-google-dns

**Comment by P1N2O** [comment]
Device Bootloops with your module.
Tested on 3 of my devices.

**Comment by Didgeridoohan** [comment]
@P1N2O try removing the placeholder file from the zip.

@tfae since you're not mounting anything to /system, you don't need AUTOMOUNT=true.

Mounting files or folders to the root of /system (that doesn't previously exist there) may cause bootloops.

**Comment by tfae** [comment]
@Didgeridoohan thank you for your input!

@P1N2O a new version is live that hopefully will not cause bootloops.

**Comment by topjohnwu** [comment]
New repo added: [magisk-google-dns](https://github.com/Magisk-Modules-Repo/magisk-google-dns), please accept the collaboration invitation in your email
