### ISSUE TITLE
[Module Submission] Unforce Camera Sound

### ISSUE THREAD

**Issue by justin97530** [topjohnwu/Magisk_Repo_Submissions#172]
Adds `ro.camera.sound.forced=0` to `boot.prop`. Helps disable screenshot sound on the Mi A1 when Total Silence is on.
https://github.com/justin97530/unforce-camera-sound

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/justin97530/unforce-camera-sound) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
