### ISSUE TITLE
Twemoji Module

### ISSUE THREAD

**Issue by Xyllon** [topjohnwu/Magisk_Repo_Submissions#173]
This module replaces system emojis with Twitter's "Twemoji".

https://github.com/Xyllon/Twemoji-systemless

Has a master branch this time, hopefully no more issues.

**Comment by topjohnwu** [comment]
New repo added: [Twemoji-systemless](https://github.com/Magisk-Modules-Repo/Twemoji-systemless), please accept the collaboration invitation in your email
