### ISSUE TITLE
[Module Submission] DNSCrypt Proxy

### ISSUE THREAD

**Issue by P1N2O** [topjohnwu/Magisk_Repo_Submissions#174]
Here is a systemless module for DNSCrypt Proxy Support.

https://github.com/P1N2O/dnscrypt-magisk

**Comment by topjohnwu** [comment]
New repo added: [dnscrypt-magisk](https://github.com/Magisk-Modules-Repo/dnscrypt-magisk), please accept the collaboration invitation in your email
