### ISSUE TITLE
[Module Submission] Hide navigation bar

### ISSUE THREAD

**Issue by AndroPlus-org** [topjohnwu/Magisk_Repo_Submissions#177]
I made simple module to hide navigation bar.
https://github.com/AndroPlus-org/magisk-module-hide-navbar

**Comment by topjohnwu** [comment]
New repo added: [magisk-module-hide-navbar](https://github.com/Magisk-Modules-Repo/magisk-module-hide-navbar), please accept the collaboration invitation in your email
