### ISSUE TITLE
[Module Submission] Wireguard Installer

### ISSUE THREAD

**Issue by ryaniskira** [topjohnwu/Magisk_Repo_Submissions#181]
Request to add Wireguard Installer to the Magisk repo.

https://github.com/ryaniskira/Wireguard-Magisk

**Comment by Didgeridoohan** [comment]
@ryaniskira

Got a bit excited when I saw this module. Been waiting to try out Wireguard... Will test this later.

One thing tough:

Why have you added wg and wg-quick to the replace part of config.sh? That's only for directories, meaning that two directories will now be created in /system/xbin (wg and wg-quick) with a .replace file inside.

If the purpose is to make sure that any original files will be removed before mounting the module files, you don't have to worry. Magisk mounts over any existing files...

**Comment by ryaniskira** [comment]
@Didgeridoohan I was lacking coffee when I did that, I removed the binaries from replace.

**Comment by RogerF81** [comment]
But it still necessary to use a kernel with in-built Wireguard support?

**Comment by topjohnwu** [comment]
New repo added: [Wireguard-Magisk](https://github.com/Magisk-Modules-Repo/Wireguard-Magisk), please accept the collaboration invitation in your email

**Comment by ryaniskira** [comment]
@RogerF81 It is not required, if your kernel doesn't support Wireguard it falls back to a different method, although it runs a bit slower. Even then it's claimed to still outperform OpenVPN.

**Comment by Didgeridoohan** [comment]
@ryaniskira

When I did a quick test it would not work, complaining that I do not have the necessary kernel support.

**Comment by ryaniskira** [comment]
@Didgeridoohan  Really? I will check the documentation again I might have misread something. I know he said something about a userspace implementation.

**Comment by Didgeridoohan** [comment]
@ryaniskira Yes. 
![screenshot_20171227-195238](https://user-images.githubusercontent.com/14870954/34390365-a85273dc-eb3f-11e7-8534-e2deeb0a08a7.jpg)
