### ISSUE TITLE
Module submission

### ISSUE THREAD

**Issue by sjayminsgithub** [topjohnwu/Magisk_Repo_Submissions#182]
I have reworked the existing module "Magic Charging Switch" from top to bottom for many code optimizations and changes, which definitely is more efficient for the purpose, here is the Repository link :-

    https://github.com/sjayminsgithub/MC-s-Charging-Controller

I'd be glad if you add this to the Magisk repository

**Comment by topjohnwu** [comment]
New repo added: [MC-s-Charging-Controller](https://github.com/Magisk-Modules-Repo/MC-s-Charging-Controller), please accept the collaboration invitation in your email
