### ISSUE TITLE
[Module Submission] DNSCrypt Proxy

### ISSUE THREAD

**Issue by barrybingo** [topjohnwu/Magisk_Repo_Submissions#183]
https://github.com/barrybingo/dnscrypt-magisk

This module does not require busybox or init.d as in  P1N2O's and this one is also multi architecture, supporting arm,arm64 and x86

Cheers.

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/barrybingo/dnscrypt-magisk) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
