### ISSUE TITLE
[Submission] ExSDCard Write Access Enabler v3

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk_Repo_Submissions#193]
https://github.com/xerta555/ExSDCard_Write_Access_Enabler_v3

**Comment by topjohnwu** [comment]
New repo added: [ExSDCard_Write_Access_Enabler_v3](https://github.com/Magisk-Modules-Repo/ExSDCard_Write_Access_Enabler_v3), please accept the collaboration invitation in your email
