### ISSUE TITLE
[Submission] ExSDCard Write Access Enabler v3 with SELinux

### ISSUE THREAD

**Issue by xerta555** [topjohnwu/Magisk_Repo_Submissions#194]
https://github.com/xerta555/ExSDCard_Write_Access_Enabler_v3_with_SELinux

**Comment by topjohnwu** [comment]
New repo added: [ExSDCard_Write_Access_Enabler_v3_with_SELinux](https://github.com/Magisk-Modules-Repo/ExSDCard_Write_Access_Enabler_v3_with_SELinux), please accept the collaboration invitation in your email
