### ISSUE TITLE
[Submission] Missing iYTBP Themed Module

### ISSUE THREAD

**Issue by zanezam** [topjohnwu/Magisk_Repo_Submissions#196]
https://github.com/zanezam/iYTBP-Vanced-black-Magisk-Repo
re-submit themed variant as it obviously got lost during merge, thx!

**Comment by topjohnwu** [comment]
New repo added: [iYTBP-Vanced-black-Magisk-Repo](https://github.com/Magisk-Modules-Repo/iYTBP-Vanced-black-Magisk-Repo), please accept the collaboration invitation in your email
