### ISSUE TITLE
EIS for Nexus 5X

### ISSUE THREAD

**Issue by PiotrDabrowskey** [topjohnwu/Magisk_Repo_Submissions#197]
Hi! Please add this module to Magisk:
https://github.com/PiotrDabrowskey/magisk-nexus5x-eis

I've tested it and works as intended. It's a replacement for the old module which is not maintained any more ([this one](https://github.com/grimsandwich/magisk-enable-eis-nexus5x))

**Comment by topjohnwu** [comment]
Unknown request title format
