### ISSUE TITLE
[Submission] EIS for Nexus 5X

### ISSUE THREAD

**Issue by PiotrDabrowskey** [topjohnwu/Magisk_Repo_Submissions#198]
https://github.com/PiotrDabrowskey/magisk-nexus5x-eis

Hi! Please add this module to Magisk. I've tested it and works as intended. It's a replacement for the old module which is not maintained any more ([this one](https://github.com/grimsandwich/magisk-enable-eis-nexus5x))

**Comment by topjohnwu** [comment]
New repo added: [magisk-nexus5x-eis](https://github.com/Magisk-Modules-Repo/magisk-nexus5x-eis), please accept the collaboration invitation in your email
