### ISSUE TITLE
[Submission] AptoidePriv

### ISSUE THREAD

**Issue by thehappydinoa** [topjohnwu/Magisk_Repo_Submissions#231]
https://github.com/thehappydinoa/AptoidePriv 
- Fixed Issue with version not being 1400

**Comment by topjohnwu** [comment]
New repo added: [AptoidePriv](https://github.com/Magisk-Modules-Repo/AptoidePriv), please accept the collaboration invitation in your email

**Comment by thehappydinoa** [comment]
Thank you!
