### ISSUE TITLE
[Submission] OOS Native Call Recording Enabler

### ISSUE THREAD

**Issue by nipunnarang** [topjohnwu/Magisk_Repo_Submissions#235]
https://github.com/nipunnarang/OOSNativeCallRecordingEnabler

**Comment by topjohnwu** [comment]
New repo added: [OOSNativeCallRecordingEnabler](https://github.com/Magisk-Modules-Repo/OOSNativeCallRecordingEnabler), please accept the collaboration invitation in your email
