### ISSUE TITLE
[Submission] Disable Xiaomi A1 navigation buttons and backlight

### ISSUE THREAD

**Issue by edmael** [topjohnwu/Magisk_Repo_Submissions#236]
https://github.com/edmael/magisk-module-a1disablebuttons

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/edmael/magisk-module-a1disablebuttons) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch

**Comment by edmael** [comment]
Hi @topjohnwu, I see the module.prop just fine in the master branch, what am I missing here?

**Comment by Didgeridoohan** [comment]
@edmael You don't even have a master branch... Only 1400, 1410, 1500 and v4. Take a look at the [readme](https://github.com/topjohnwu/Magisk_Repo_Submissions/blob/master/README.MD) again.

**Comment by edmael** [comment]
@Didgeridoohan sorry, I'm kind of new to the GitHub system.
I re-read the documentation and fixed the branch problem on my repository, shall I open a new issue?

Thanks for your time, have a nice day.

**Comment by Didgeridoohan** [comment]
@edmael Yes, open a new issue and it should be included in the repo soon.

**Comment by edmael** [comment]
Thanks, have a nice day!
