### ISSUE TITLE
[Submission] APT-X for Oreo module

### ISSUE THREAD

**Issue by Jolanrensen** [topjohnwu/Magisk_Repo_Submissions#241]
A while back I created a module to enable apt-x on Oreo devices that don't already have it. I decided to update it to Magisk 15 and add it to the repo.

https://github.com/Jolanrensen/APT-X-Oreo

**Comment by topjohnwu** [comment]
New repo added: [APT-X-Oreo](https://github.com/Magisk-Modules-Repo/APT-X-Oreo), please accept the collaboration invitation in your email
