### ISSUE TITLE
[Submission] Magisk Manager for Recovery Mode (mm)

### ISSUE THREAD

**Issue by VR-25** [topjohnwu/Magisk_Repo_Submissions#243]
https://github.com/VR-25/Magisk-Manager-for-Recovery-Mode

**Comment by topjohnwu** [comment]
New repo added: [Magisk-Manager-for-Recovery-Mode](https://github.com/Magisk-Modules-Repo/Magisk-Manager-for-Recovery-Mode), please accept the collaboration invitation in your email
