### ISSUE TITLE
[Submission] PixelWifi Module

### ISSUE THREAD

**Issue by RogerF81** [topjohnwu/Magisk_Repo_Submissions#262]
[PixelWifi](https://github.com/RogerF81/pennygetyourownwifi)

I think I got it now xD Sorry again, didn't want to bother you!

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/RogerF81/pennygetyourownwifi)) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch

**Comment by RogerF81** [comment]
o.O module.prop is there on master branch?!
