### ISSUE TITLE
[Submission] PixelWiFi Module

### ISSUE THREAD

**Issue by RogerF81** [topjohnwu/Magisk_Repo_Submissions#263]
[PixelWiFi](https://github.com/RogerF81/pennygetyourownwifi)

Last try. Must have benn EOL issues in previous tries.

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/RogerF81/pennygetyourownwifi)) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
