### ISSUE TITLE
[Submission] Camera Lag Fix MI A1

### ISSUE THREAD

**Issue by Addicted5** [topjohnwu/Magisk_Repo_Submissions#266]
https://github.com/Addicted5/MI-A1-Camera-Startup-Lag-Oreo

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/Addicted5/MI-A1-Camera-Startup-Lag-Oreo) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
