### ISSUE TITLE
[Submission] MI A1 Camera Lag Oreo

### ISSUE THREAD

**Issue by Addicted5** [topjohnwu/Magisk_Repo_Submissions#267]
https://github.com/Addicted5/MI-A1-Camera-Startup-Lag-Oreo

**Comment by topjohnwu** [comment]
New repo added: [MI-A1-Camera-Startup-Lag-Oreo](https://github.com/Magisk-Modules-Repo/MI-A1-Camera-Startup-Lag-Oreo), please accept the collaboration invitation in your email
