### ISSUE TITLE
Request for a new Repo

### ISSUE THREAD

**Issue by LolloOlearo** [topjohnwu/Magisk_Repo_Submissions#271]
Hi,
i've forked your repo and created a new module that change the system font into Myraid Pro, could it be added to Magisk-Modules-Repo?
Thanks so much, this is mine repo link: https://github.com/LolloOlearo/magisk-module-swypelibs

**Comment by topjohnwu** [comment]
Unknown request title format

**Comment by LolloOlearo** [comment]
How the request title format should be?

On Feb 13, 2018 2:50 PM, "John Wu" <notifications@github.com> wrote:

Unknown request title format

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/topjohnwu/Magisk_Repo_Submissions/issues/271#issuecomment-365271798>,
or mute the thread
