### ISSUE TITLE
[Submission] JF Sans Font

### ISSUE THREAD

**Issue by aldam05** [topjohnwu/Magisk_Repo_Submissions#275]
https://github.com/aldam05/JF-Sans-Font

**Comment by Zackptg5** [comment]
If you're trying to make a new module, you need to add [Submission] to the front of the issue name

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/aldam05/JF-Sans-Font) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
