### ISSUE TITLE
[Submission] Google Answers Enabler

### ISSUE THREAD

**Issue by daradan** [topjohnwu/Magisk_Repo_Submissions#276]
https://github.com/daradan/GoogleAnswersEnabler

**Comment by Zackptg5** [comment]
The name of the issue should be the name of your module (Google Answers Enabler or something)

**Comment by daradan** [comment]
Sorry. I changed issues name.

**Comment by thehappydinoa** [comment]
You have to re do it

**Comment by daradan** [comment]
@thehappydinoa what do u by "redo it?" man,i actually i didn't get ur point. will be much appreciated if u  specify it. thanks

**Comment by thehappydinoa** [comment]
Oh what I meant is that there is a magisk repo bot that checks the original name of the issue for submission or removal
