### ISSUE TITLE
[Submission] Google Sans Mod Font

### ISSUE THREAD

**Issue by aldam05** [topjohnwu/Magisk_Repo_Submissions#282]
https://github.com/aldam05/GSansMod

**Comment by skittles9823** [comment]
Do we really need another google sans installer in the repo though? This one reuses fonts where they aren't supposed to be used too.

**Comment by topjohnwu** [comment]
New repo added: [GSansMod](https://github.com/Magisk-Modules-Repo/GSansMod), please accept the collaboration invitation in your email
