### ISSUE TITLE
[Submission] Assertive Display Enabler

### ISSUE THREAD

**Issue by jordiid96** [topjohnwu/Magisk_Repo_Submissions#293]
https://github.com/jordiid96/assertive-display

**Comment by Didgeridoohan** [comment]
You should really tidy up your modules before submitting...

Example: Looks like they all identify as "Youtube UHD Enabler" during installation and this one has a readme that states "ART Optimizations". It also looks like all your submitted modules make use of the system.prop file, but it's not activated in a single one of them.

**Comment by Didgeridoohan** [comment]
And by the way... A more descriptive readme might also be useful.
