### ISSUE TITLE
[Submission] A New Module !!

### ISSUE THREAD

**Issue by hifzhan41** [topjohnwu/Magisk_Repo_Submissions#298]
[Recent_App_Grid_Mode.zip](https://github.com/topjohnwu/Magisk_Repo_Submissions/files/1799718/Recent_App_Grid_Mode.zip)

**Comment by skittles9823** [comment]
You're supposed to link your GitHub repo, not add a direct download. Also the readme wasn't changed from the module you used as a base. Tbh all these one line build prop modules are getting old and aren't needed on the repo, if you are going to upload one add a bit more in it or make a mega thread on XDA with these buildprop modules.

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/topjohnwu/Magisk_Repo_Submissions/files/1799718/Recent_App_Grid_Mode.zip)) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
