### ISSUE TITLE
[Submission] Ruthless Pixel Launcher

### ISSUE THREAD

**Issue by skittles9823** [topjohnwu/Magisk_Repo_Submissions#306]
https://github.com/skittles9823/ruthless-pixel-launcher 

Also add https://github.com/shubhchan as a contributor.

**Comment by topjohnwu** [comment]
New repo added: [ruthless-pixel-launcher](https://github.com/Magisk-Modules-Repo/ruthless-pixel-launcher), please accept the collaboration invitation in your email
