### ISSUE TITLE
[Submission] Daydream-for-sony-f5121

### ISSUE THREAD

**Issue by GlassedSilver** [topjohnwu/Magisk_Repo_Submissions#315]
https://github.com/GlassedSilver/magisk-module-daydream-for-sony-f5121

**Comment by topjohnwu** [comment]
New repo added: [magisk-module-daydream-for-sony-f5121](https://github.com/Magisk-Modules-Repo/magisk-module-daydream-for-sony-f5121), please accept the collaboration invitation in your email
