### ISSUE TITLE
[Submission] FaceID for Redmi Note 4 (mido)

### ISSUE THREAD

**Issue by shubhandu** [topjohnwu/Magisk_Repo_Submissions#317]
https://github.com/shubhandu/FaceID-Magisk_module-RN4-mido

**Comment by topjohnwu** [comment]
New repo added: [FaceID-Magisk_module-RN4-mido](https://github.com/Magisk-Modules-Repo/FaceID-Magisk_module-RN4-mido), please accept the collaboration invitation in your email
