### ISSUE TITLE
[Submission] New module fixing Play Store device certification status

### ISSUE THREAD

**Issue by ttimasdf** [topjohnwu/Magisk_Repo_Submissions#318]
https://github.com/ttimasdf/playstore_certification_bypass

Fix by injecting proper build fingerprint per device.

Currently supported:
- OnePlus 3
- Samsung Note 4 N9100
- OnePlus 2

**Comment by topjohnwu** [comment]
New repo added: [playstore_certification_bypass](https://github.com/Magisk-Modules-Repo/playstore_certification_bypass), please accept the collaboration invitation in your email
