### ISSUE TITLE
[Submission] DCI_P3 Color Mode For OP3T

### ISSUE THREAD

**Issue by OROKIN** [topjohnwu/Magisk_Repo_Submissions#327]
https://github.com/OROKIN/DCI_P3-Color-Mode-For-OP3T

**Comment by topjohnwu** [comment]
New repo added: [DCI_P3-Color-Mode-For-OP3T](https://github.com/Magisk-Modules-Repo/DCI_P3-Color-Mode-For-OP3T), please accept the collaboration invitation in your email
