### ISSUE TITLE
[Submission] Xiaomi Mi Mix 2 Snapchat Volume Fix

### ISSUE THREAD

**Issue by arghhhhh** [topjohnwu/Magisk_Repo_Submissions#331]
https://github.com/arghhhhh/mix-2-snapchat-volume-fix.git

**Comment by topjohnwu** [comment]
New repo added: [mix-2-snapchat-volume-fix](https://github.com/Magisk-Modules-Repo/mix-2-snapchat-volume-fix), please accept the collaboration invitation in your email
