### ISSUE TITLE
[Submission] A new module !!!

### ISSUE THREAD

**Issue by JonasCardoso** [topjohnwu/Magisk_Repo_Submissions#352]
https://github.com/JonasCardoso/gpsconfO

**Comment by xerta555** [comment]
Hello,
I think u should create two issues for your two modules, as u have 2 different repos on your git, if u want that theses new modules be present in Magisk Repo:

![submission](https://raw.githubusercontent.com/topjohnwu/Magisk_Repo_Submissions/master/images/submission.png)

Although the server configuration should read your issue line by line according the source code:

`const parseProp = (data) => {
  let arr = data.split('\n');
  let ret = {};
  arr.forEach((line) => {
    let s = line.split('=');
    if (s.length != 2)
      return;
    ret[s[0]] = s[1];
  })
  return ret;

}`

[https://github.com/topjohnwu/Magisk_Repo_Submissions/blob/master/server.js](https://github.com/topjohnwu/Magisk_Repo_Submissions/blob/master/server.js)

I hope your issue will be accepted by the server as topjohnwu don't let his physical computer alive everytime..

**Comment by Didgeridoohan** [comment]
@JonasCardoso You should also include a README.MD file in your modules.

**Comment by JonasCardoso** [comment]
@Didgeridoohan finished both
https://github.com/JonasCardoso/gpsconfN
https://github.com/JonasCardoso/gpsconfO

**Comment by sjayminsgithub** [comment]
@xerta555, maybe you mistook the code for parsing the module.prop file as parsing the issue body. The server.js sources does not allow multiple github repos in a single issue. Please see the processIssue function that does that which doesn't allow multiple GitHub links.
