### ISSUE TITLE
[Submission] ro.build.type to user

### ISSUE THREAD

**Issue by pongo1231** [topjohnwu/Magisk_Repo_Submissions#353]
https://github.com/pongo1231/magisk-buildtype-to-user

**Comment by ShadySquirrel** [comment]
Isn't Magisk Hide changing it to 'user' as soon as you enable it?

**Comment by Didgeridoohan** [comment]
@ShadySquirrel Yes, it does. 

Where you aware of this @pongo1231? I guess this could be useful if you don't have MagiskHide active, but I'm guessing those users are quite few...

**Comment by pongo1231** [comment]
Huh. I even checked what ro.build.type was set to before creating this as I also already thought Magisk Hide set it to "user". Weirdly enough it was set to "userdebug" for me.

**Comment by Didgeridoohan** [comment]
In that case you have an issue with MagiskHide on your device...

**Comment by Didgeridoohan** [comment]
@pongo1231 You sure you want to keep this module in here, for inclusion in the Magisk repo?

**Comment by pongo1231** [comment]
I guess if there is no interest for this module, I am going to close it down.

**Comment by Didgeridoohan** [comment]
It's not that there's no interest for it, but there shouldn't be any use for it...
